import { Inter } from "next/font/google";
import "./scss/__index.scss";
import "normalize.css/normalize.css";
// import { ThemeProvider } from "./context/ThemeContext";
import { CounterProvider } from "./components/zLearning/ServerClient/CounterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterProvider>{children}</CounterProvider>;
        {/* <ThemeProvider>{children}</ThemeProvider> */}
      </body>
    </html>
  );
}
