"use client";
import { createContext, useState } from "react";

export const CounterContext = createContext(0);

export const CounterProvider = ({ children }) => {
  const [count, setCount] = useState(0);

  return <CounterContext.Provider>{children}</CounterContext.Provider>;
};

// layout.js

// import { Inter } from "next/font/google";
// import "./scss/__index.scss";
// import "normalize.css/normalize.css";
// import { CounterProvider } from "./CounterContext";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//        <CounterProvider>{children}</CounterProvider>;
//         {/* <ThemeProvider>{children}</ThemeProvider> */}
//       </body>
//     </html>
//   );
// }
